pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for softwaremill-ci pull requests affecting build.sbt
    conditions:
      - author=softwaremill-ci
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for softwaremill-ci pull requests affecting project plugins.sbt
    conditions:
      - author=softwaremill-ci
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for softwaremill-ci pull requests affecting project scalafmt.conf
    conditions:
      - author=softwaremill-ci
      - status-success=continuous-integration/travis-ci/pr
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
  - name: semi-automatic merge for softwaremill-ci pull requests
    conditions:
      - author=softwaremill-ci
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
